name: game
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gif: ^2.3.0
  flutter_cache_manager: ^3.3.1
  lottie: ^3.1.0
  dotted_line: ^3.2.2
  flutter_launcher_icons: ^0.13.1
  video_player: ^2.8.6
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  get: ^4.6.6
  audioplayers: ^5.2.1
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/close.svg
    - assets/icons/speaker.svg
    - assets/Confetti-original.json

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 100

